### PR TITLE
[AMORO-2852]: fix eslint error & eslint config

### LINKED ISSUE #2852: [Improvement]: Improve eslint rules and fix
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Standardize the format and style of code written by everyone

### How should we improve?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhangmo8**
## Why are the changes needed?

fix eslint error & eslint config

Close #2852 .

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: amoro-ams/amoro-ams-dashboard/src/components/tables-sub-menu/TablesMenu.vue [hunk 1]
```diff
@@ -338,12 +277,81 @@ export default defineComponent({
...
+          </div>
+          <u-loading v-if="loading" />
+          <VirtualRecycleScroller :loading="loading" :items="databaseList" :active-item="database" :item-size="40" icon-name="database" @handle-click-table="handleClickDb" />
+        </div>
+      </div>
+      <div class="table-list">
+        <div class="list-wrap">
+          <div class="add g-flex-jsb">
+            <span class="label">{{ $t('table', 2) }}</span>
+            <!-- <plus-outlined @click="createTable" class="icon" /> -->
```
Comment (chouchouji) [inline amoro-ams/amoro-ams-dashboard/src/components/tables-sub-menu/TablesMenu.vue:329]: It would be better to delete this useless content.

**Review by chouchouji — APPROVED** [review]

**Review by zhoujinsong — APPROVED** [review]
LGTM.

Thanks for the work! @zhangmo8 
Thanks for the review! @chouchouji
