### PR TITLE
[AMORO-3754]failed to failover when only one node is alive in ha mode #3754

### LINKED ISSUE #3754: [Bug]: failed to failover when only one node is alive in ha mode
### What happened?

Image

### Affects Versions

0.8.x

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. enable ha mode
2. keep only one ams instance 
3. Simulate ZooKeeper session timeout
4. may be ten tables are written, and optimizing is processing.
This is intermittent and does not occur consistently.

### Relevant log output

```shell

```

### Anything else

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Aireed**
## Why are the changes needed?

Close #3754 .

## Brief change log

- call stop regardless of whether the service is serving
- unregister metric key before registration

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: amoro-ams/src/main/java/org/apache/amoro/server/metrics/MetricRegistry.java [hunk 1]
```diff
@@ -78,6 +78,7 @@ public <T extends Metric> MetricKey register(
         define.getName());
 
     MetricKey key = new MetricKey(define, tags);
+    unregister(key);
```
Comment (baiyangtx) [inline amoro-ams/src/main/java/org/apache/amoro/server/metrics/MetricRegistry.java]: I believe an `unregister` method should be provided and called by the metrics registrant during disposal, rather than performing the unregister action at registration time.

File: amoro-ams/src/main/java/org/apache/amoro/server/AmoroServiceContainer.java [hunk 2]
```diff
@@ -200,11 +200,11 @@ private void addHandlerChain(RuntimeHandlerChain chain) {
   }
 
   public void disposeOptimizingService() {
-    if (tableManagementServer != null && tableManagementServer.isServing()) {
+    if (tableManagementServer != null) {
```
Comment (zhoujinsong) [inline amoro-ams/src/main/java/org/apache/amoro/server/AmoroServiceContainer.java:208]: It seems the codebase is out of date, comparing with the master branch:https://github.com/apache/amoro/blob/master/amoro-ams/src/main/java/org/apache/amoro/server/AmoroServiceContainer.java#L208

File: amoro-ams/src/main/java/org/apache/amoro/server/metrics/MetricRegistry.java (hunk 1 above)
Comment (zhoujinsong) [reply amoro-ams/src/main/java/org/apache/amoro/server/metrics/MetricRegistry.java]: +1
