### PR TITLE
[AMORO-3110] Avoid optimization status blocking in running

### LINKED ISSUE #3110: [Bug]: Optimization state blocking in running
### What happened?

When the insertion into table `optimizing_task_quota` fails, subsequent logic cannot proceed because all database operations are wrapped in the same session. Even if the exception is caught, `com.netease.arctic.server.persistence.NestedSqlSession#isRollingback` will still be true.Therefore, an exception will be thrown when checking the session status in `org.apache.amoro.server.persistence.NestedSqlSession#checkState`. So the table optimization status is stuck in running.

### Affects Versions

master

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS

### How to reproduce

_No response_

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rfyu**
## Why are the changes needed?

Close #3110.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java [hunk 1]
```diff
@@ -468,6 +468,7 @@ public void acceptResult(TaskRuntime taskRuntime) {
         }
       } catch (Exception e) {
         LOG.error("accept result error:", e);
+        throw e;
```
Comment (zhoujinsong) [inline amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java:471]: I agree that we should throw the exception rather than just printing logs.
But we may just remove the catch blocks because we will print error logs in the service proxy.

File: amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/TableRuntime.java [hunk 2]
```diff
@@ -409,7 +409,7 @@ private boolean updateConfigInternal(Map<String, String> properties) {
   }
 
   public void addTaskQuota(TaskRuntime.TaskQuota taskQuota) {
-    doAs(OptimizingMapper.class, mapper -> mapper.insertTaskQuota(taskQuota));
+    doAsAlone(OptimizingMapper.class, mapper -> mapper.insertTaskQuota(taskQuota));
```
Comment (zhoujinsong) [inline amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/TableRuntime.java:412]: It seems we started another transaction to update the quota.
Another method to solve this issue is using the same transaction and ignoring the persistent error. We can add a method like `doAsIgnoreError` in PersistentBase to get that.

What do you think is the better method? @rfyu

**Review by zhoujinsong — COMMENTED** [review]
@rfyu Thanks for trying to solve this issue.

I left some comments, PTAL.

File: amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/TableRuntime.java (hunk 2 above)
Comment (rfyu) [reply amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/TableRuntime.java:412]: thanks for your suggestion. It is acceptable to handle it using the same transaction. I will make the necessary modifications accordingly.

**Comment by zhoujinsong** [comment]
LGTM.

However, there are some conflicts that should be fixed. @rfyu

**Review by zhoujinsong — APPROVED** [review]
LGTM.
