### PR TITLE
[AMORO-3885] fix missing oss.endpoint for internal mixed_iceberg catalog

### LINKED ISSUE #3885: [Bug]: Lost oss.endpoint for internal catalog with mixed_iceberg format
### What happened?

CatalogController::constructCatalogMeta does not correctly setup oss.endpoint to catalog properties

### Affects Versions

master

### What table formats are you seeing the problem on?

Mixed-Iceberg

### What engines are you seeing the problem on?

AMS

### How to reproduce

create/update catalog request, using mixed_iceberg format and oss storage

### Relevant log output

```shell

```

### Anything else

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by liaoyt**
## Why are the changes needed?

Close #3885.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/CatalogController.java [hunk 1]
```diff
@@ -500,7 +500,8 @@ private CatalogMeta constructCatalogMeta(CatalogRegisterInfo info, CatalogMeta o
           STORAGE_CONFIGS_KEY_S3_ENDPOINT,
           S3FileIOProperties.ENDPOINT);
     } else if (storageType.equals(STORAGE_CONFIGS_VALUE_TYPE_OSS)) {
-      if (TableFormat.valueOf(tableFormats) == TableFormat.ICEBERG) {
+      if (Arrays.asList(TableFormat.ICEBERG, TableFormat.MIXED_ICEBERG)
```
Comment (zhoujinsong) [inline amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/CatalogController.java]: `tableFormats` would be a string variable that contains multiple table formats like `ICEBERG,MIXED_ICEBERG,PAIMON`. We may change the code here to `info.getTableFormatList().contains(ICEBERG.name()) || info.getTableFormatList().contains(MIXED_ICEBERG.name())`.

HDYT?
BTW, the line 509 should be fixed too.

**Review by zhoujinsong — COMMENTED** [review]
Thanks for the contribution!
I left a comment, PTAL.

File: amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/CatalogController.java (hunk 1 above)
Comment (liaoyt) [reply amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/CatalogController.java]: you are right, i had fixed this and also the get catalog detail interface should be fixed too
