### PR TITLE
[AMORO-3533] Avoid bulk table removal when synchronizing external catalogs and fetching database table listings fails

### LINKED ISSUE #3533: [Improvement]: Avoid bulk table removal when synchronizing external catalogs and fetching database table listings fails
### Search before asking

- [x] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently when synchronizing the external directory and fetching the database table list fails, the database is considered to contain 0 tables and triggers all its tables to be removed. However, when synchronizing the external directory and fetching the database tables again and succeeds, it triggers the process of adding all the tables. When there are a large number of tables in the database, this can lead to significant thread resource usage and page update delays.

In the logs, we see something like this
> 2025-04-16 10:39:52,974 INFO [table-explorer-scheduler-0] [org.apache.amoro.server.table.DefaultTableService] [] - Loaded 0 tables from external catalog my_catalog.
2025-04-16 10:39:54,269 INFO [table-explorer-scheduler-0] [org.apache.amoro.server.table.DefaultTableService] [] - Loaded 8307 tables from Amoro server catalog my_catalog.
2025-04-16 10:39:54,271 INFO [table-explorer-executor-24] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - Release queue my_catalog with table my_catalog.my_database.mid_woff_balance_72_20240401(tableId=6661580)
2025-04-16 10:39:54,271 INFO [table-explorer-executor-40] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - Release queue my_catalog with table my_catalog.my_database.mid_acct_balance_76_20240406(tableId=6661620)
2025-04-16 10:39:54,271 INFO [table-explorer-executor-14] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - Release queue my_catalog with table my_catalog.my_database.mid_woff_balance_72_20240402(tableId=6661607)
2025-04-16 10:39:54,271 INFO [table-explorer-executor-39] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - Release queue my_catalog with table my_catalog.my_database.mid_acct_balance_76_20240407(tableId=6661591)
2025-04-16 10:39:54,271 INFO [table-explorer-executor-17] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - Release queue my_catalog with table my_catalog.my_database.mid_acct_balance_76_20240409(tableId=6661603)
2025-04-16 10:39:54,271 INFO [table-explorer-executor-21] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - Release queue my_catalog with table my_catalog.my_database.mid_acct_balance_76_20240408(tableId=6661597)
2025-04-16 10:39:54,271 INFO [table-explorer-executor-6] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - Release queue my_catalog with table my_catalog.my_database.mid_woff_balance_72_20240403(tableId=6661592)
2025-04-16 10:39:54,271 INFO [table-explorer-executor-35] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - Release queue my_catalog with table my_catalog.my_database.mid_woff_balance_72_20240404(tableId=6661596)
2025-04-16 10:39:54,271 INFO [table-explorer-executor-1] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - Release queue my_catalog with table my_catalog.my_database.mid_acct_balance_76_20240402(tableId=6661576)
2025-04-16 10:39:54,271 INFO [table-explorer-executor-0] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - Release queue my_catalog with table my_catalog.my_database.mid_acct_balance_76_20240403(tableId=6661619)
2025-04-16 10:39:54,271 INFO [table-explorer-executor-45] [org.apache.amoro.server.optimizing.OptimizingQueue] [] - Release queue my_catalog with table my_catalog.my_database.mid_acct_balance_76_20240405(tableId=6661611)
......

### How should we improve?

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Jzjsnow**
## Why are the changes needed?

Currently when synchronizing the external directory and fetching the database table list fails, an empty `HashSet` is returned in `DefaultTableService#exploreExternalCatalog()`, which causes the database to be considered to contain 0 tables and triggers the removal of all its tables.

Close #3533.

## Brief change log

- Throw an exception instead of returning an empty set when fetching the list of tables for a database fails.

## How was this patch tested?

- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: amoro-ams/src/test/java/org/apache/amoro/server/table/TestSyncTableOfExternalCatalog.java [hunk 1]
```diff
@@ -239,6 +257,194 @@ public void testSynchronizationWithLegacyTableRuntimeAndNonExistingIcebergTable(
...
+  @Test
+  public void exploreExternalCatalog_ListTablesException() {
+    createTable();
+    ServerCatalog originalCatalog = catalogManager().getServerCatalog(TEST_CATALOG_NAME);
+
+    // test list tables
+    List<TableRuntimeMeta> tableRuntimeMetaListAfterAddTable = persistency.getTableRuntimeMetas();
+    Assert.assertEquals(1, tableRuntimeMetaListAfterAddTable.size());
+
+    MockitoAnnotations.openMocks(this);
```
Comment (klion26) [inline amoro-ams/src/test/java/org/apache/amoro/server/table/TestSyncTableOfExternalCatalog.java:303]: Currently, there are many `mock`s in the tests; we can avoid `mock`s as much as possible because using mocks may prevent the test from sensing actual changes and thus fail to initiate corresponding actions.

But this does not need to be done in this PR, we can do it later.

**Review by klion26 — APPROVED** [review]
LGTM, thanks for the fix

File: amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableService.java [hunk 2]
```diff
@@ -275,18 +274,24 @@ public void exploreExternalCatalog(ExternalCatalog externalCatalog) {
...
-                            return new HashSet<>();
-                          }
-                        },
-                        tableExplorerExecutors));
+                            () -> {
+                              try {
+                                return externalCatalog.listTables(database).stream()
+                                    .map(TableIdentity::new)
+                                    .collect(Collectors.toSet());
+                              } catch (Exception e) {
```
Comment (zhoujinsong) [inline amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableService.java:282]: Hi，can we remove this try-catch here as we already handled the exception with the `exceptionally ` call?

**Review by zhoujinsong — COMMENTED** [review]
Thanks for the contribution, I left a comment, PTAL.

**Comment by zhoujinsong** [comment]
Thanks for the contribution! @Jzjsnow
