### PR TITLE
[AMORO-3111]Avoid optimization state blocking in planning

### LINKED ISSUE #3111: [Bug]: Optimization state blocking in planning
### What happened?

The exception thrown by the `org.apache.amoro.server.optimizing.OptimizingQueue#planInternal` was not handled, and the catch content will also cause an exception because the jdbc connection is not obtained. So the table is always in the running state.
image

### Affects Versions

master

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS

### How to reproduce

_No response_

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rfyu**
## Why are the changes needed?

Close #3111.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/TableRuntime.java [hunk 1]
```diff
@@ -188,13 +188,21 @@ public void beginPlanning() {
...
+          () -> {
+            OptimizingStatus originalStatus = optimizingStatus;
+            updateOptimizingStatus(OptimizingStatus.PENDING);
+            persistUpdatingRuntime();
+            tableHandler.handleTableChanged(this, originalStatus);
+          });
+    } catch (Exception e) {
+      OptimizingStatus originalStatus = optimizingStatus;
+      updateOptimizingStatus(OptimizingStatus.PENDING);
+      LOG.error(
```
Comment (zhoujinsong) [inline amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/TableRuntime.java:202]: Warn logging level may be proper here.

File: amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/AmoroManagementConf.java [hunk 2]
```diff
@@ -299,7 +299,7 @@ public class AmoroManagementConf {
   public static final ConfigOption<Long> DB_CONNECT_MAX_WAIT_MILLIS =
       ConfigOptions.key("database.connection-pool-max-wait-millis")
           .longType()
-          .defaultValue(1000L)
+          .defaultValue(-1L)
```
Comment (zhoujinsong) [inline amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/AmoroManagementConf.java:302]: We may need to roll back the change here.

**Review by zhoujinsong — COMMENTED** [review]
@rfyu Thanks for the contribution, I left some comments, PTAL.

**Review by zhoujinsong — APPROVED** [review]
LGTM.
