### PR TITLE
[AMORO-3253] Optijmizing getOPtimizingProcessTasks and getOptimizingTypes rest efficiency

### LINKED ISSUE #3253: [Improvement]: Optimizing getOptimizingProcessTasks and getOptimizingTypes
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

we'll  1) check whether the table exists in  `TableController#getOptimizingTypes` and `TableController#getOptimizingProcessTasks`, 2) and load the table in the following step to get the desired info.
step 2 will check if the table exists and throw an exception if the table does not exist.
the table exists check will load the table from the catalog which may be something too expansive.

### How should we improve?

Remove the tableExists check in `TableController#getOptimizingTypes` and `TableController#getOptimizingProcessTasks`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by klion26**
## Why are the changes needed?

Close #3253.

## Brief change log
Before the change we'll check whether the table exists by loading the table, the loading step maybe too expensive, and it's redundant because the table exists will be checked in the folllowing step when loading table to retrieve the info.

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

### CODE REVIEW

File: amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/TableController.java [hunk 1]
```diff
@@ -338,8 +338,6 @@ public void getOptimizingTypes(Context ctx) {
     String db = ctx.pathParam("db");
```
Comment (klion26) [inline amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/TableController.java:338]: the `serverCatalog.tableExists` in line 322 will be addressed in #3066

**Review by majin1102 — APPROVED** [review]
LGTM

**Comment by klion26** [comment]
@majin1102 thanks for the review and merging!
