### PR TITLE
[AMORO-3545] Prevent empty tasks list during planning

### LINKED ISSUE #3545: [Bug]: AMS stops optimizing when some partitions have high cost but cannot be scheduled
### What happened?

In AbstractOptimizingPlanner, once the number of inputs exceeds maxInputSize, additional partition evaluators are dropped—yet at least one evaluator is always retained.

However, if the remaining evaluators only reference unschedulable tasks (for example, in IcebergPartitionPlan when a task has just a single data file), the planner will produce no output, even though the original evaluator list included valid tasks.

This happens because the logic is two staged and doesn't consider the task eligibility when pruning partitions.

### Affects Versions

master

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS

### How to reproduce

_No response_

### Relevant log output

```shell

```

### Anything else

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lrsb**
Fix #3545 

This change merges the logic in AbstractOptimizingPlanner to avoid having `actualPartitionPlans` with only unschedulable tasks.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [X] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? no
- If yes, how is the feature documented? not applicable

### CODE REVIEW

File: amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java [hunk 1]
```diff
@@ -158,19 +158,23 @@ public List<RewriteStageTask> planTasks() {
...
     long actualInputSize = 0;
+    double avgThreadCost = actualInputSize / availableCore;
+    List<RewriteStageTask> tasks = Lists.newArrayList();
+
     for (PartitionEvaluator evaluator : evaluators) {
-      actualPartitionPlans.add((AbstractPartitionPlan) evaluator);
-      actualInputSize += evaluator.getCost();
+      AbstractPartitionPlan actualPartitionPlan = (AbstractPartitionPlan) evaluator;
+      List<RewriteStageTask> splitTasks =
+          actualPartitionPlan.splitTasks((int) (actualInputSize / avgThreadCost));
```
Comment (klion26) [inline amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java:167]: It is ok to change this currently, because the parameter for `splitTasks` is not taken into consideration, but maybe in the future we will change the logic in `TaskSplitter#splitTasks`

Can we change the `actualInputSize / avgThreadCost` here to some other things like `evaluator.getCost() / avgThreadCostPre` -- but currently there is no `avgThreadCostPre` 

Maybe we can add a comment here to let others know we need to change this here? what do you think about this

File: amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java [hunk 2]
```diff
@@ -158,19 +158,23 @@ public List<RewriteStageTask> planTasks() {
     double maxInputSize = maxInputSizePerThread * availableCore;
     actualPartitionPlans = Lists.newArrayList();
     long actualInputSize = 0;
+    double avgThreadCost = actualInputSize / availableCore;
```
Comment (klion26) [inline amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java:161]: I have a question about the change here.

Is the change here mainly to correct the log at the end of this function? is my understanding right?

Before the change, if the `tasks` is empty because there are no tasks after `actualPartitionPlan.splitTasks`, then there would be no actual optimization executed because we will check whether the `tasks` are empty or not in `AbstractOptimizingPlanner#isNecessary` and `OptimizingQueue#loadTaskRuntimes`.
- After the change, the `tasks` will be empty also, but the `actualInputSize` is the right value.

If this is the case, can we correct the calculation logic for `actualInputSize`?

**Review by klion26 — COMMENTED** [review]
@lrsb thanks for the contribution, I left some inline comments, please take a look when you're free.

File: amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java (hunk 1 above)
Comment (lrsb) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java:167]: I see what you mean, will publish another review.

Regarding the comment I think it should be placed in the implementation classes.

File: amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java (hunk 2 above)
Comment (lrsb) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java:161]: > Is the change here mainly to correct the log at the end of this function?

No the issue is different:
- Let's say there's a PartitionEvaluator which output of splitTasks is empty (because, for example in Iceberg, it contains only one data file)
- Let's also say its cost is > maxInputSize

The result is that:
- actualPartitionPlans will contain just that evaluator even if there are more in the initial list
- Since split tasks output is empty nothing will be scheduled
- If this keeps happening we get into a starvation like situation where the first evaluator keeps getting scheduled but nothing is actually executed even if the initial list there are schedulable evaluators

> After the change, the tasks will be empty also, but the actualInputSize is the right value.

No, the output after the change will be populated with the other partition evaluators

Comment (klion26) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java]: Thanks for the explain.

**Comment by klion26** [comment]
@lrsb thanks for the update. The change looks fine to me. Please refine the code style to pass the style check in CI.

File: amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java [hunk 3]
```diff
@@ -151,27 +151,31 @@ public List<RewriteStageTask> planTasks() {
       return cacheAndReturnTasks(Collections.emptyList());
     }
 
-    List<PartitionEvaluator> evaluators = new ArrayList<>(needOptimizingPlanMap.values());
+    LinkedList<PartitionEvaluator> evaluators = new LinkedList<>(needOptimizingPlanMap.values());
```
Comment (klion26) [inline amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java:154]: do you think we need to update the `needOptimizingPlanMap` after the plan

File: amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java [hunk 4]
```diff
@@ -151,27 +151,33 @@ public List<RewriteStageTask> planTasks() {
...
```
[the remark this answers is not in the document]
Comment (lrsb) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java]: changed to priority queue since makes more sense given we are sorting too

[the remark this answers is not in the document]
Comment (xxubai) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java]: I think using a `Deque` is sufficient here, as a priority queue is not more efficient than a list in this case, especially during polling. Therefore, I don’t think using a priority queue for sorting is necessarily appropriate.

**Review by xxubai — APPROVED** [review]

File: amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java [hunk 5]
```diff
@@ -151,27 +151,33 @@ public List<RewriteStageTask> planTasks() {
...
-      if (actualInputSize > maxInputSize) {
-        break;
+    List<RewriteStageTask> plannedTasks = Lists.newArrayList();
+
+    while (plannedTasks.isEmpty() && !evaluators.isEmpty()) {
+      for (PartitionEvaluator evaluator = evaluators.poll();
+          evaluator != null;
+          evaluator = evaluators.poll()) {
+        actualPartitionPlans.add((AbstractPartitionPlan) evaluator);
+        actualInputSize += evaluator.getCost();
```
Comment (zhoujinsong) [inline amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java:168]: Nice catch!

But I am wondering if we should calculate the input size depending on the real tasks from plannedTasks rather than `evaluator#cost` if the cost is not true.
