### PR TITLE
[AMORO-3218] Fix logic for consturct the result of optimizer tables api

### LINKED ISSUE #3218: [Bug]: optimizing Tab paging display error
### What happened?

image
No matter how many items are selected to be displayed per page, there will only be one page in the end.

### Affects Versions

master

### What table formats are you seeing the problem on?

_No response_

### What engines are you seeing the problem on?

AMS

### How to reproduce

_No response_

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by klion26**
## Why are the changes needed?

Close #3218 .

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request
image

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by klion26** [comment]
cc @huyuanfeng2018 @zhoujinsong @majin1102

File: amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableService.java [hunk 1]
```diff
@@ -471,6 +471,11 @@ public TableRuntime getRuntime(Long tableId) {
     return tableRuntimeMap.get(tableId);
   }
 
+  public int getRuntimeCount() {
```
Comment (huyuanfeng2018) [inline amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableService.java:474]: What if we have filters?
For example, database is specified in search

Comment (klion26) [reply amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableService.java]: @huyuanfeng2018 thanks for pointing this out, fix it.

**Review by huyuanfeng2018 — APPROVED** [review]
LGTM. @klion26  There are some conflicts that need to be resolved

File: amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/OptimizerController.java [hunk 2]
```diff
@@ -75,10 +76,15 @@ public void getOptimizerTables(Context ctx) {
     List<TableRuntime> tableRuntimes =
         tableRuntimeBeans.stream()
             .map(meta -> tableService.getRuntime(meta.getTableId()))
+            .filter(Objects::nonNull)
```
Comment (majin1102) [inline amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/OptimizerController.java:79]: Since we are using the in-memory table runtime list, why do we still need to query the ID list from the database and get list count from memory? 
It seems quite fragmented

File: amoro-ams/src/main/java/org/apache/amoro/server/table/TableManager.java [hunk 3]
```diff
@@ -33,6 +35,9 @@ public interface TableManager extends TableRuntimeHandler {
 
   TableRuntime getRuntime(Long tableId);
 
+  /** Get the count of table runtimes associated to the given filter. */
+  int getRuntimeCount(@Nullable String dbFilter, @Nullable String tableFilter);
```
Comment (majin1102) [inline amoro-ams/src/main/java/org/apache/amoro/server/table/TableManager.java:39]: I think instead of defining such an interface, it would be better to directly define a listRuntimes interface.

**Review by majin1102 — CHANGES_REQUESTED** [review]
Thanks for your contributions

I left some comments, PTAL

File: amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/OptimizerController.java (hunk 2 above)
Comment (klion26) [reply amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/OptimizerController.java:79]: Yes, this is defensive programming, because we will process the information we get here(TableRuntime list) later and throw Exception in `OptimizingUtil#buildTableOptimizeInfo`), of course, we can also remove it here if needed

**Comment by klion26** [comment]
@majin1102 I've addressed the comments, please take another look when you're free. thanks.

**Review by majin1102 — APPROVED** [review]
LGTM

**Comment by klion26** [comment]
@huyuanfeng2018 @majin1102 thanks for the review and merging!
