### PR TITLE
[AMORO-3637] Complete task when optimizer get an exception in task execution

### LINKED ISSUE #3637: [Subtask]: Complete task when optimizer get an exception in task execution
### Search before asking

- [x] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description
Currently, when the optimizer is encountered with an unexpected throws an exception during the execution of a task, it only logs “Optimizer executor[xx] got an unexpected error”, and doesn't call ams about the completion of the task. The task on ams is stuck in the ACK status and the optimization process is stuck at MINOR/MAJOR/FULL.

When the optimizer throws an exception during the execution of a task, it‘s better to notify ams the completion of the task.

### Parent issue

#3636

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Jzjsnow**
## Why are the changes needed?

Close #3637.

## Brief change log

- Notify the ams of the completion of the task as long as the task is successfully acknowledged.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java [hunk 1]
```diff
@@ -241,10 +241,11 @@ public void ackTask(String authToken, int threadId, OptimizingTaskId taskId) {
   @Override
   public void completeTask(String authToken, OptimizingTaskResult taskResult) {
     LOG.info(
-        "Optimizer {} (threadId {}) complete task {}",
+        "Optimizer {} (threadId {}) complete task {}, result: {}",
```
Comment (xxubai) [inline amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java]: The `taskOutput` in the taskResult is unreadable. Can we simplify the result information?

File: amoro-optimizer/amoro-optimizer-common/src/main/java/org/apache/amoro/optimizer/common/OptimizerExecutor.java [hunk 2]
```diff
@@ -112,9 +132,10 @@ protected void completeTask(OptimizingTaskResult optimizingTaskResult) {
             return null;
           });
       LOG.info(
-          "Optimizer executor[{}] completed task[{}] to ams",
+          "Optimizer executor[{}] completed task[{}] to ams, taskResult: {}",
```
Comment (xxubai) [inline amoro-optimizer/amoro-optimizer-common/src/main/java/org/apache/amoro/optimizer/common/OptimizerExecutor.java]: Same above

File: amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java (hunk 1 above)
Comment (Jzjsnow) [reply amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java]: Yep, `taskOutput` is not readable, and here we are more concerned about whether the task succeeded or not, which is determined by the `ErrorMessage` being null. However, the logged `"result: {}"` here may be ambiguous, I can change it to `"status: [SUCCESS|FAIL]"` for more clarity, HDYT?

File: amoro-optimizer/amoro-optimizer-common/src/main/java/org/apache/amoro/optimizer/common/OptimizerExecutor.java [hunk 3]
```diff
@@ -50,8 +50,28 @@ public void start() {
       try {
         OptimizingTask task = pollTask();
         if (task != null && ackTask(task)) {
-          OptimizingTaskResult result = executeTask(task);
```
Comment (xxubai) [inline amoro-optimizer/amoro-optimizer-common/src/main/java/org/apache/amoro/optimizer/common/OptimizerExecutor.java:53]: Why do we need an additional try-catch block here, given that `executeTask(task)` already returns an error result when an exception occurs?

Comment (Jzjsnow) [reply amoro-optimizer/amoro-optimizer-common/src/main/java/org/apache/amoro/optimizer/common/OptimizerExecutor.java:53]: I remove the additional try-catch block in the new commit, and reuse the original try-catch block. The `completeTask(result)` method is now placed in the finally block to ensure that the task can complete in ams as long as the task is successfully acknowledged, regardless of whether an exception occurs during execution. PTAL

File: amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java [hunk 4]
```diff
@@ -241,10 +241,11 @@ public void ackTask(String authToken, int threadId, OptimizingTaskId taskId) {
   @Override
   public void completeTask(String authToken, OptimizingTaskResult taskResult) {
     LOG.info(
-        "Optimizer {} (threadId {}) complete task {}",
+        "Optimizer {} (threadId {}) complete task {} (status: {})",
         authToken,
         taskResult.getThreadId(),
-        taskResult.getTaskId());
+        taskResult.getTaskId(),
+        taskResult.getErrorMessage() == null ? "SUCCESS" : "FAIL");
```
Comment (klion26) [inline amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java:248]: nit: we may reuse `TaskRuntime.Status.SUCCESS` and `TaskRuntime.Status.FAILED` instead of hard coding.

**Review by klion26 — APPROVED** [review]
Thanks for the contribution, LGTM
