### PR TITLE
[AMORO-2862] fix bug: A null pointer error occurs when using S3 as Storage when using the kyuubi terminal.

### LINKED ISSUE #2862: [Bug]: A null pointer error occurs when using S3 as Storage when using the kyuubi terminal.
### What happened?

A null pointer error occurs when using S3 as Storage when using the kyuubi terminal.
image
image

### Affects Versions

master/0.6.0

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. Use S3 as internal catalog
2. Use kyuubi to use this catalog

### Relevant log output

```shell
2024-05-24 16:05:55,652 INFO [terminal-execute-1] [com.netease.arctic.server.terminal.kyuubi.KyuubiTerminalSessionFactory] [] - 
2024-05-24 16:05:55,652 ERROR [terminal-execute-1] [com.netease.arctic.server.terminal.TerminalSessionContext] [] - something error when execute script. 
java.lang.NullPointerException: null
        at java.util.Hashtable.put(Hashtable.java:460) ~[?:1.8.0_312]
        at com.netease.arctic.server.terminal.kyuubi.KyuubiTerminalSessionFactory.create(KyuubiTerminalSessionFactory.java:126) ~[amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.server.terminal.TerminalSessionContext.lazyLoadSession(TerminalSessionContext.java:165) ~[amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.server.terminal.TerminalSessionContext.access$200(TerminalSessionContext.java:40) ~[amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.server.terminal.TerminalSessionContext$ExecutionTask.lambda$get$0(TerminalSessionContext.java:198) ~[amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.table.TableMetaStore.call(TableMetaStore.java:234) ~[amoro-core-0.6.0.jar:?]
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:207) ~[amoro-core-0.6.0.jar:?]
        at com.netease.arctic.server.terminal.TerminalSessionContext$ExecutionTask.get(TerminalSessionContext.java:196) [amoro-ams-server-0.6.0.jar:?]
        at com.netease.arctic.server.terminal.TerminalSessionContext$ExecutionTask.get(TerminalSessionContext.java:171) [amoro-ams-server-0.6.0.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by upczsh**
## Why are the changes needed?

Close #2862.

## Brief change log

- A null pointer error occurs when using S3 as Storage when using the kyuubi terminal.Determine in the kyuubi terminal. If the catalog type is s3 type, then do not add hadoopusername to avoid null pointer errors.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate
**Before repair：**
image

**after repair：**
image

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/kyuubi/KyuubiTerminalSessionFactory.java [hunk 1]
```diff
@@ -124,8 +125,11 @@ public TerminalSession create(TableMetaStore metaStore, Configurations configura
     Properties properties = new Properties();
 
     if (!metaStore.isKerberosAuthMethod()) {
-      properties.put(JdbcConnectionParams.AUTH_USER, metaStore.getHadoopUsername());
```
Comment (zhoujinsong) [inline amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/kyuubi/KyuubiTerminalSessionFactory.java:127]: How about checking if the value is null before putting it into properties and configuration?
I think it will be simpler if we fix it this way.

**Review by zhoujinsong — COMMENTED** [review]
@upczsh Thanks for reporting this bug and trying to fix it.

I left some comments, PTAL.

File: amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/kyuubi/KyuubiTerminalSessionFactory.java (hunk 1 above)
Comment (XBaith) [reply amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/kyuubi/KyuubiTerminalSessionFactory.java:127]: +1

Comment (upczsh) [reply amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/kyuubi/KyuubiTerminalSessionFactory.java:127]: Thank you for your suggestion, I have made the changes.

Comment (XBaith) [reply amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/kyuubi/KyuubiTerminalSessionFactory.java:127]: We can use one condition to fix this, WDYT

Comment (upczsh) [reply amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/kyuubi/KyuubiTerminalSessionFactory.java:127]: > We can use one condition to fix this, WDYT

Okay, I've merged it into one.thinks.
