### PR TITLE
[ARCTIC-1451][Bug]: When the target column doesn't contain primary key, reading from Arctic Filestore will encounter NullPointerException. 

### LINKED ISSUE #1451: [Bug]: When the target column doesn't contain primary key, reading from Arctic Filestore will encounter NullPointerException.
### What happened?

When the target column doesn't contain primary key, reading from Arctic Filestore will encounter NullPointerException.

### Affects Versions

master

### What engines are you seeing the problem on?

Flink

### How to reproduce

```
create table arctic_catalog.test.tb (
    id int,
    user_id int, 
    street string,
    user_name string,
    primary key (id)
) using arctic;

create table print_tb(
    user_id int, 
    street string
) WITH (
'connector' = 'print'
);

insert into print_tb 
select user_id, street from arctic_catalog.test.tb 
where user_id > 1000;
```

### Relevant log output

```shell
java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:199)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:154)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:116)
	at com.netease.arctic.flink.read.hybrid.reader.ArcticSourceReader.pollNext(ArcticSourceReader.java:128)
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:275)
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:67)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:398)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:191)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:619)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:583)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:758)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:573)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:146)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.lang.NullPointerException
	at com.netease.arctic.data.PrimaryKeyData.<init>(PrimaryKeyData.java:57)
	at com.netease.arctic.utils.NodeFilter.<init>(NodeFilter.java:45)
	at com.netease.arctic.io.reader.AbstractIcebergDataReader.<init>(AbstractIcebergDataReader.java:91)
	at com.netease.arctic.hive.io.reader.AbstractAdaptHiveIcebergDataReader.<init>(AbstractAdaptHiveIcebergDataReader.java:76)
	at com.netease.arctic.flink.read.source.FlinkArcticDataReader.<init>(FlinkArcticDataReader.java:66)
	at com.netease.arctic.flink.read.hybrid.reader.RowDataReaderFunction.createDataIterator(RowDataReaderFunction.java:87)
	at com.netease.arctic.flink.read.hybrid.reader.DataIteratorReaderFunction.apply(DataIteratorReaderFunction.java:42)
	at com.netease.arctic.flink.read.hybrid.reader.DataIteratorReaderFunction.apply(DataIteratorReaderFunction.java:31)
	at com.netease.arctic.flink.read.hybrid.reader.HybridSplitReader.fetch(HybridSplitReader.java:67)
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:56)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:138)
	... 6 more
```

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lklhdu**
## Why are the changes needed?
The reason for this error is that the iceberg table schema doesn't contain identifierFieldIds when the table is created via Spark, which causes Flink to fail in adding the primary key.
fix #1451 

## Brief change log

  - *Populate primary key fields for Flink Schema by PrimaryKeySpec*
  - *Replacing schema-related constructor calls in ArcticSparkCatalog*
  - *The flink 1.12, 1.14 and 1.15 versions are affected.*

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

File: core/src/main/java/com/netease/arctic/utils/SchemaUtil.java [hunk 1]
```diff
@@ -48,17 +51,21 @@ public static Schema changeWriteSchema(Schema changeTableSchema) {
...
    */
-  public static Schema fillUpIdentifierFields(Schema baseSchema, Schema fromSchema) {
+  public static Schema fillUpIdentifierFields(Schema baseSchema, Schema fromSchema, PrimaryKeySpec primaryKeySpec) {
     int schemaId = fromSchema.schemaId();
     Types.StructType struct = fromSchema.asStruct();
     List<Types.NestedField> fields = Lists.newArrayList(struct.fields());
-    Set<Integer> identifierFields = baseSchema.identifierFieldIds();
-    identifierFields.forEach(fieldId -> {
+    Set<Integer> identifierFieldIds = Sets.newHashSet(baseSchema.identifierFieldIds());
+    List<String> primaryKeys = primaryKeySpec.fields().stream()
```
Comment (YesOrNo828) [inline core/src/main/java/com/netease/arctic/utils/SchemaUtil.java:59]: Could you combine the `map` and `forEach` iterators together?

**Review by YesOrNo828 — APPROVED** [review]
LGTM
