### PR TITLE
[AMORO-2977]Mixed-Format Unkeyed Table will read the full amount of data even if configured with 'scan.startup.mode'='latest' 

### LINKED ISSUE #2977: [Bug]: Mixed-Format Unkeyed Table will read the full amount of data even if configured with 'scan.startup.mode'='latest'
### What happened?

When I read an unkeyed amoro table of type mixed-format through Flink, I found that even with the 'scan.startup.mode'='latest' configuration item configured, the full amount of data is read, which is not a situation that meets expectations.

### Affects Versions

master

### What table formats are you seeing the problem on?

Mixed-Iceberg, Mixed-Hive

### What engines are you seeing the problem on?

Flink

### How to reproduce

1. Create an unkeyed table of type mixed-format
```
create table test_db.test_table (
    id int,
    name string, 
    age int
) using mixed_hive;
```
2. Write several initial data
```
insert into test_db.test_table values (1,'name1',10);
insert into test_db.test_table values (2,'name2',10);
```
3. Set 'scan.startup.mode' to latest to start reading data from the current latest snapshot
```
select * from test_db.test_table
/*+ OPTIONS('streaming'='true','arctic.read.mode'='file','source.parallelism' = '1','table.format'='MIXED_HIVE','scan.startup.mode'='latest') */;
```
But it will read the full amount of data, not as expected.

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lklhdu**
## Why are the changes needed?
Fix #2977.

## Brief change log

- When 'scan.startup.mode'='latest'  is configured, read the unkeyed amoro table of type mixed-format based on the current snapshot ID

## How was this patch tested?

- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

File: amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/table/FlinkSource.java [hunk 1]
```diff
@@ -214,17 +223,40 @@ private void loadTableIfNeeded() {
...
+      Preconditions.checkArgument(
+          Objects.isNull(scanStartupMode)
+              || Objects.equals(scanStartupMode, MixedFormatValidator.SCAN_STARTUP_MODE_EARLIEST)
+              || Objects.equals(scanStartupMode, SCAN_STARTUP_MODE_LATEST),
+          String.format(
+              "only support %s, %s when %s is %s",
+              MixedFormatValidator.SCAN_STARTUP_MODE_EARLIEST,
+              SCAN_STARTUP_MODE_LATEST,
+              MixedFormatValidator.MIXED_FORMAT_READ_MODE,
+              MixedFormatValidator.MIXED_FORMAT_READ_FILE));
```
Comment (baiyangtx) [inline amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/table/FlinkSource.java:237]:
```suggestion
      scanStartupMode = scanStartupMode == null ? null : scanStartupMode.toLowerCase();
      Preconditions.checkArgument(
          Objects.isNull(scanStartupMode)
              || Objects.equals(scanStartupMode, MixedFormatValidator.SCAN_STARTUP_MODE_EARLIEST)
              || Objects.equals(scanStartupMode, MixedFormatValidator.SCAN_STARTUP_MODE_LATEST),
          String.format(
              "only support %s, %s when %s is %s",
              MixedFormatValidator.SCAN_STARTUP_MODE_EARLIEST,
              MixedFormatValidator.SCAN_STARTUP_MODE_LATEST,
              MixedFormatValidator.MIXED_FORMAT_READ_MODE,
              MixedFormatValidator.MIXED_FORMAT_READ_FILE));
```

**Review by zhoujinsong — APPROVED** [review]
LGTM.

Thanks for the contribution!
