### PR TITLE
[AMORO-2811][Bug][FLINK]: flink unified catalog doesn't support mixed_hive

### LINKED ISSUE #2811: [Bug][FLINK]: flink  unified catalog doesn't support mixed_hive
### What happened?

SQL like this:
```
CREATE CATALOG unifiedCatalog WITH (
'type' = 'unified',
'metastore.url' = 'thrift://xxxx:pppp/unified_catalog'
)

create table if not exists unifiedCatalog.iceberg_test.mh_by_uc_spark_test(
id int,
name string,
dt string,
primary key (id,dt) not enforced
) with ('write.upsert.enabled'='true');
```

we encounted the error 

image

### Affects Versions

master

### What engines are you seeing the problem on?

Flink

### How to reproduce

```
CREATE CATALOG unifiedCatalog WITH (
'type' = 'unified',
'metastore.url' = 'thrift://xxxx:pppp/unified_catalog'
)

create table if not exists unifiedCatalog.iceberg_test.mh_by_uc_spark_test(
id int,
name string,
dt string,
primary key (id,dt) not enforced
) with ('write.upsert.enabled'='true');
```

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Aireed**
## Why are the changes needed?

Close #2811 .

## Brief change log

```
create table if not exists xxxx (
....
);
```
A unifiedCatalog which metastore is hms.
- when create a mixed-hive table:
  - If there is a table in mixed-hive format with the same name, the program can execute correctly with no error thrown and the table is not overwrited;
  - If there is a table in hive format with the same name, the program will throw an error, 
  - If there is no table with the same name, a mixed-hive table will be created.
- when create a iceberg table
  -  if there is a table in iceberg format with the same name, the program can execute correctly with no error ,and the table is not overwrited;
  -  If there is no table with the same name, a iceberg table will be created.
  
- when create a mixed-iceberg table
  - If there is a table in iceberg format with the same name, the program can execute correctly with no error thrown and the table is not overwrited;
  -  If there is a table in hive format with the same name, the program should thrown an error to indicate the table does exist;
  -  If there is no table with the same name, an iceberg table will be created.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by Aireed** [comment]
cc @YesOrNo828  @xieyi888   PTAL.

File: amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java [hunk 1]
```diff
@@ -221,8 +226,25 @@ public void createTable(ObjectPath tablePath, CatalogBaseTable table, boolean ig
...
+        format = amoroTable.format();
+      } catch (Throwable t) {
+        LOG.warn(
+            "We can't load table {}.{} through unifiedCatalog, use default format {}",
+            tablePath.getDatabaseName(),
+            tablePath.getObjectName(),
+            format.name());
+      }
+    }
+    final TableFormat catalogFormat = format;
```
Comment (baiyangtx) [inline amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java:244]: This method is used to create a table. How to load the table before creating it?

File: amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java [hunk 2]
```diff
@@ -221,8 +226,25 @@ public void createTable(ObjectPath tablePath, CatalogBaseTable table, boolean ig
...
+      try {
+        AmoroTable amoroTable =
+            unifiedCatalog.loadTable(tableIdentifier.getDatabase(), tableIdentifier.getTableName());
+        format = amoroTable.format();
+      } catch (Throwable t) {
+        LOG.warn(
+            "We can't load table {}.{} through unifiedCatalog, use default format {}",
+            tablePath.getDatabaseName(),
+            tablePath.getObjectName(),
+            format.name());
```
Comment (xieyi888) [inline amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java:241]: if can't load table
we should get default format use default table_format 
`format = configuration.get(TABLE_FORMAT)`

File: amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java [hunk 3]
```diff
@@ -221,8 +226,25 @@ public void createTable(ObjectPath tablePath, CatalogBaseTable table, boolean ig
...
         TableIdentifier.of(
             unifiedCatalog.name(), tablePath.getDatabaseName(), tablePath.getObjectName());
+    if (!configuration.contains(TABLE_FORMAT)) {
+      // if user doesn't specify the table format, we try to load the table and get the table
+      // format.
+      try {
+        AmoroTable amoroTable =
+            unifiedCatalog.loadTable(tableIdentifier.getDatabase(), tableIdentifier.getTableName());
+        format = amoroTable.format();
+      } catch (Throwable t) {
```
Comment (xieyi888) [inline amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java:236]: maybe
```catch (org.apache.amoro.NoSuchTableException e) 
```
would be better

File: amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java [hunk 4]
```diff
@@ -221,8 +226,25 @@ public void createTable(ObjectPath tablePath, CatalogBaseTable table, boolean ig
...
+            tablePath.getDatabaseName(),
+            tablePath.getObjectName(),
+            format.name());
+      }
+    }
+    final TableFormat catalogFormat = format;
     AbstractCatalog catalog =
-        getOriginalCatalog(format).orElseGet(() -> createOriginalCatalog(tableIdentifier, format));
+        getOriginalCatalog(format)
+            .orElseGet(() -> createOriginalCatalog(tableIdentifier, catalogFormat));
```
Comment (xieyi888) [inline amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java:247]: If table exists, we load table and get tableFormat for it, Otherwise, we use default tableFormat to create table, which is MIXED_ICEBERG.

Did we should force user to add 'table.format' option in create table statement?

File: amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java (hunk 1 above)
Comment (Aireed) [reply amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java:244]: > This method is used to create a table. How to load the table before creating it?
```
  public void createTable(ObjectPath tablePath, CatalogBaseTable table, boolean ignoreIfExists)
```
In the Flink SQL scenario, when users are writing SQL, this situation arises when they use "create table if not exists" to define a table that already exists. The parameter "ignoreIfExists" is used to ignore the existence of the table.

File: amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java (hunk 4 above)
Comment (Aireed) [reply amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java:247]: > Did we should force user to add 'table.format' option in create table statement?
Good idea. If the table cannot be loaded via unifiedCatalog and no format is specified, we should report an error to prompt the user to specify the format. WDYT?

File: amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java [hunk 5]
```diff
@@ -221,8 +226,25 @@ public void createTable(ObjectPath tablePath, CatalogBaseTable table, boolean ig
     TableIdentifier tableIdentifier =
         TableIdentifier.of(
             unifiedCatalog.name(), tablePath.getDatabaseName(), tablePath.getObjectName());
+    if (!configuration.contains(TABLE_FORMAT)) {
```
Comment (baiyangtx) [inline amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java:229]:
```suggestion
    if (!configuration.contains(TABLE_FORMAT) && ignoreIfExists && unfiiedCatalog.tableExists()) {
```

File: amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java (hunk 4 above)
Comment (baiyangtx) [reply amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java:247]: I think we could support a property of catalog which define a defult table format when creating a table without specific the format.

Comment (Aireed) [reply amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java:247]: > I think we could support a property of catalog which define a defult table format when creating a table without specific the format.

IMO, Configuring the format on both the table and the catalog at the same time can easily mislead users. The "Unified Catalog" is designed to allow users not to worry about the underlying format (except when it is created).

Let's listen to some other opinions.   WDYT  @YesOrNo828  @xieyi888

File: amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java (hunk 5 above)
Comment (Aireed) [reply amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java:229]: Even when the user applies the "create table xxx()" statement to create a table, it is still necessary to validate the format of the table. So there is no need to add additional conditions.

File: amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java [hunk 6]
```diff
@@ -221,8 +226,26 @@ public void createTable(ObjectPath tablePath, CatalogBaseTable table, boolean ig
...
+      } catch (NoSuchTableException | NoSuchDatabaseException e) {
+        String msg =
+            String.format(
+                "Can't decide table format of table %s, Please specify 'table.format' "
+                    + "in table properties",
+                tableIdentifier.toString());
+        throw new CatalogException(msg);
+      }
+    }
+    final TableFormat catalogFormat = format;
```
Comment (baiyangtx) [inline amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java:245]:
```suggestion
    Preconditions.checkNotNull(format, "Lack required property: table-format");
    if(ignoreIfExists) {
      try {
          AmoroTable amoroTable =
              unifiedCatalog.loadTable(tableIdentifier.getDatabase(), tableIdentifier.getTableName());
          return;
        } catch (NoSuchTableException) {
          // do nothing
        }
    }
```

**Review by baiyangtx — APPROVED** [review]
LGTM, thanks for your contributions.
