### PR TITLE
[AMORO-3673][Improvement]: Try to commit the optimizing process upon failure or cancellation

### LINKED ISSUE #3673: [Improvement]: Optimizing the submission of some successful self-optimizing tasks
### Search before asking

- [x] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

If some self-optimizing tasks in a table optimizing process fail or the process is canceled, the results of the successfully completed optimizing tasks will be discarded. In such cases, it is possible to submit the results of these completed tasks to avoid wasting optimizer resources.

### How should we improve?

The proposed changes are detailed in the AIP document: https://docs.google.com/document/d/143Wktb_5CmOAt-NHQoeGuP_9JUwIfc7r3_716wYTbC8/edit?usp=sharing

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cxxiii**
## Why are the changes needed?

Close #3673 .

## Brief change log

- To prevent optimizer resource wastage, we propose submitting the results of successfully completed tasks in cases where the optimizing process fails because a task has exceeded the maximum number of retry attempts, or when the process is manually cancelled by the user.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by klion26** [comment]
@cxxiii could you please rebase the latest master, so that we can start to review this.

**Comment by cxxiii** [comment]
> @cxxiii could you please rebase the latest master, so that we can start to review this.

Thank you and I have rebased the branch onto the latest master. Please proceed with the review.

File: amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingProcess.java [hunk 1]
```diff
@@ -44,7 +44,11 @@ public interface OptimizingProcess {
 
   long getRunningQuotaTime(long calculatingStartTime, long calculatingEndTime);
 
+  boolean containSuccessTasks();
```
Comment (zhoujinsong) [inline amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingProcess.java]: I am not sure if we need this public method, it seems it is only called inner the impelemenation.

File: amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingProcess.java [hunk 2]
```diff
@@ -44,7 +44,11 @@ public interface OptimizingProcess {
...
+
   void commit();
 
+  void commitClosedProcess();
```
Comment (zhoujinsong) [inline amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingProcess.java]: Can we reuse the `commit` method? I don't see the need to implement a method exclusively for the process closing case.

File: amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java [hunk 3]
```diff
@@ -507,14 +507,32 @@ private void acceptResult(TaskRuntime<?> taskRuntime) {
...
-            LOG.info(
-                "Task {} has reached the max execute retry count. Process {} failed.",
-                taskRuntime.getTaskId(),
-                processId);
-            this.failedReason = taskRuntime.getFailReason();
-            this.status = ProcessStatus.FAILED;
-            this.endTime = taskRuntime.getEndTime();
-            persistAndSetCompleted(false);
+            try {
+              buildCommit().commit();
```
Comment (zhoujinsong) [inline amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java]: I don't think we should perform the commit action directly here. Instead, we should delegate the commit process to the `OptimizingCommitExecutor`, just like how we handle normal commits currently.

File: amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingProcess.java (hunk 1 above)
Comment (cxxiii) [reply amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingProcess.java]: I think this public method is necessary, because we called this method through the interface in other classes.

File: amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingProcess.java (hunk 2 above)
Comment (cxxiii) [reply amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingProcess.java]: Your suggestion is good, I have made changes.

File: amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java (hunk 3 above)
Comment (cxxiii) [reply amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java]: Your suggestion is good, I have made changes.

File: amoro-format-iceberg/src/main/java/org/apache/amoro/table/TableProperties.java [hunk 4]
```diff
@@ -72,6 +72,10 @@ private TableProperties() {}
 
   public static final boolean ENABLE_SELF_OPTIMIZING_DEFAULT = true;
 
+  public static final String SELF_OPTIMIZING_COMMIT_ON_PARTIAL_SUCCESS =
+      "self-optimizing.commit-on-partial-success";
+  public static final boolean SELF_OPTIMIZING_COMMIT_ON_PARTIAL_SUCCESS_DEFAULT = true;
```
Comment (zhoujinsong) [inline amoro-format-iceberg/src/main/java/org/apache/amoro/table/TableProperties.java]: I suggest making the default value false , as it is a new feature.

Comment (zhoujinsong) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/table/TableProperties.java]: And is `self-optimizing.allow-partial-commit` a proper name?

File: amoro-ams/src/main/java/org/apache/amoro/server/optimizing/UnKeyedTableCommit.java [hunk 5]
```diff
@@ -245,6 +256,17 @@ public void commit() throws OptimizingCommitException {
     }
   }
 
+  private boolean needRemove(
```
Comment (zhoujinsong) [inline amoro-ams/src/main/java/org/apache/amoro/server/optimizing/UnKeyedTableCommit.java]: Perhaps we should proactively identify the delete files that need to be excluded in advance, rather than iterate through the task map each time to improve efficiency.

**Review by zhoujinsong — COMMENTED** [review]
@cxxiii I left some comments, PTAL.

File: amoro-format-iceberg/src/main/java/org/apache/amoro/table/TableProperties.java (hunk 4 above)
Comment (cxxiii) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/table/TableProperties.java]: Good suggestions.

File: amoro-ams/src/main/java/org/apache/amoro/server/optimizing/UnKeyedTableCommit.java (hunk 5 above)
Comment (cxxiii) [reply amoro-ams/src/main/java/org/apache/amoro/server/optimizing/UnKeyedTableCommit.java]: Ok, I will consider and modify it.

**Review by zhoujinsong — APPROVED** [review]
LGTM.
