### PR TITLE
[AMORO-2932] fix prometheus exporter issues in helm chart

### LINKED ISSUE #2932: [Bug]: Can not deploy prometheus reporter via helm chart
### What happened?

Plugin name does not conform to k8s service name specification

### Affects Versions

master

### What table format are you seeing the problem on?

_No response_

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. Enable prometheus reporter
2. Deploy AMS via helm chart

### Relevant log output

```shell
Error: UPGRADE FAILED: cannot patch "ams" with kind Deployment: Deployment.apps "ams" is invalid: spec.template.spec.containers[0].ports[3].name: Invalid value: "prometheus-exporter": must be no more than 15 characters
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by XBaith**
## Why are the changes needed?

Close #2932 .

## Brief change log

- Can report metrics via prometheus in k8s

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not documented)

### CODE REVIEW

File: amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java [hunk 1]
```diff
@@ -52,9 +52,10 @@ public void close() {
     this.server.close();
   }
 
+  /** {@inheritDoc} */
   @Override
   public String name() {
-    return "prometheus-exporter";
+    return "prometheus";
```
Comment (zhoujinsong) [inline amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java:58]: `prometheus ` seems to be ambiguous. I am not sure if the service name must be the same with the plugin name.

Comment (XBaith) [reply amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java:58]: Yes it is. AMS need to load the plugin class base on the name, and plugin name is same as property name in configmap

Comment (baiyangtx) [reply amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java:58]: When I first used the -exporter suffix considering because that we might implement a reporter based on push-gateway in the future.

Comment (baiyangtx) [reply amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java:58]: What's problem for '-' in kubernetes ?

Comment (XBaith) [reply amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java:58]: '-' is valid, the problem is the name should be less than 15 characters

Comment (czy006) [reply amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java:58]: '-' is valid +1 ,can use other replace it

Comment (baiyangtx) [reply amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java:58]: Do we have to use SVC to expose exporter in K8S?
What are the common ways to integrate Promethues in K8S?

Comment (XBaith) [reply amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java:58]: prometheus push-gateway has limitations for some scenarios and not fitable for long-lived jobs(refer to https://prometheus.io/docs/practices/pushing/#should-i-be-using-the-pushgateway). I suggest we use prometheus  operator + podmonitor to achive this

Comment (zhoujinsong) [reply amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java:58]: How about `prom-exporter`? exporter seems to be an important part of the plugin name.

Comment (XBaith) [reply amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java:58]: @zhoujinsong I think it's fine, as long as it's stated that it's an abbreviation of prometheus

Comment (XBaith) [reply amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java:58]: @baiyangtx How about adding a additional property `portName` which can be used as `containerPort` in deployment and `port` in podmonitor
```
plugin:
  metricReporters:
    - name: prometheus-exporter
      enabled: true
      properties:
        port: 7001
        portName: metrics # which is hereby normatively defined as https://datatracker.ietf.org/doc/html/rfc6335#section-5.1
        interval: 60s
      service:
        type: ClusterIP
        port: "7001"
        nodePort: ~
        annotations: {
          "prometheus.io/scrape": "true",
          "prometheus.io/path": "/metrics",
          "prometheus.io/port": "7001"
        }
```

Comment (XBaith) [reply amoro-ams/amoro-ams-metrics/amoro-metrics-prometheus/src/main/java/org/apache/amoro/metrics/promethues/PrometheusMetricsReporter.java:58]:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: amoro-monitor
  name: amoro-monitor
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    {{- range .Values.plugin.metricReporters }}
    - interval: {{ .properties.interval }}
      port: {{ .properties.portName }}
    {{- end}}
  selector:
    matchLabels:
      app.kubernetes.io/name: ams
```

**Comment by baiyangtx** [comment]
In this PR, can we simply handle the problem and only adapt helm charts for promethues?

```
metricReporters:
    promethues-exporter:
        enabled: true
        port: 7001
        properties: ~
```

and in deployment.yaml 

```
          ports:
            - name: rest
              containerPort: {{ .Values.server.rest.port }}
            - name: table
              containerPort: {{ .Values.server.table.port }}
            - name: optimizing
              containerPort: {{ .Values.server.optimizing.port }}
            {{- include "amoro.pod.container.ports" . | nindent 8 }}

```

and we can manager port in _pod.tpl 

```
{{- define "amoro.pod.container.ports" -}}
            - name: rest
              containerPort: {{ .Values.server.rest.port }}
            - name: table
              containerPort: {{ .Values.server.table.port }}
            - name: optimizing
              containerPort: {{ .Values.server.optimizing.port }}
{{- if .Values.metricRepoerters.promethuesExporter.enabled -}} 
            - name: promethues
              containerPort: {{ .Values.metricRepoerters.promethuesExporter.port }}
{{- end -}}
{{- end -}}
```

**Comment by XBaith** [comment]
@baiyangtx  PTAL

**Review by baiyangtx — APPROVED** [review]
LGTM

**Comment by zhoujinsong** [comment]
Thanks for the work. @XBaith 
Thanks for the review. @baiyangtx
