### PR TITLE
Fixed the issue where the process table was completed after AMS restart, but the table status remained in the running state.

### LINKED ISSUE #4041: [Bug]: Restarting AMS may cause the table to remain in the running state indefinitely and never transition to another status.
### What happened?

After restarting the AMS pod, we found that some tables had actually completed the minor process, but their status remained as "minor" and would never change from this state.

Image

Image

### Affects Versions

0.8.0

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

Spark

### How to reproduce

When the table is in the committing state and the AMS pod is restarted, there is a chance of encountering this issue.

### Relevant log output

```shell

```

### Anything else

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lintingbin**
## Why are the changes needed?

Close #4041.

## Brief change log

- Initialize the TableOptimizingProcess to retrieve the Process Status from the database instead of using the default RUNNING status.
- In the initTableRuntime, determine whether the Process Status is successful. If successful, perform the complete process operation.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java [hunk 1]
```diff
@@ -141,6 +141,9 @@ private void initTableRuntime(DefaultTableRuntime tableRuntime) {
               mapper -> mapper.getProcessState(tableRuntime.getProcessId()));
       process = new TableOptimizingProcess(tableRuntime, meta, state);
       tableRuntime.recover(process);
+      if (process.getStatus() == ProcessStatus.SUCCESS) {
```
Comment (klion26) [inline amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java]: Will place this logic in `tableRuntime.recover(process)` be better?

File: amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java [hunk 2]
```diff
@@ -500,6 +503,7 @@ public TableOptimizingProcess(
       if (processState.getToSequence() != null) {
         toSequence = processState.getToSequence();
       }
+      this.status = processMeta.getStatus();
```
Comment (klion26) [inline amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java:503]: Just curious, why do we need this?

Comment (lintingbin) [reply amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java:503]: The default status is currently ProcessStatus.RUNNING. During initialization, the correct state was not properly retrieved from the database. Here, we are only restoring the state from the database.

File: amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java (hunk 1 above)
Comment (lintingbin) [reply amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java]: That makes sense, I've made the changes

**Review by klion26 — APPROVED** [review]
Thanks for the quick update, LGTM, will merge it in next week if there are no more comments from the community.

File: amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java
Comment (lintingbin) [inline amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java:143]: @klion26 Do you know why there is also tableRuntime.recover in the initialization function of TableOptimizingProcess? It looks a bit strange, doesn't it? Maybe we should optimize it?
```
      if (this.status != ProcessStatus.KILLED) {
        tableRuntime.recover(this);
      }
```

Comment (klion26) [reply amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java:143]: I don't have a strict preference for these two; these two are both ok to me, they are like different code styles to me.

**Comment by klion26** [comment]
Thanks for the contribution again! @lintingbin
