### PR TITLE
[AMORO-4044] Fix partition mapping bug in TableEntriesScan for tables with evolved PartitionSpec

### LINKED ISSUE #4044: [Bug]: For Iceberg tables whose PartitionSpec has been changed, Amoro will throw an error when executing the clean-dangling-delete-files operation.
### What happened?

We have a Flink job that performs CDC synchronization from an upstream database to Iceberg. This job generates many equality delete files, and many of them are dangling delete files. When Amoro runs the clean-dangling-delete-files operation on this table, it fails with the following error.
```
2026-01-14 02:49:39,401 WARN [async-dangling-delete-files-cleaning-executor-7] [org.apache.amoro.server.optimizing.maintainer.IcebergTableMaintainer] [] - Failed to commit dangling delete file for table $catalog.$database.$table, but ignore it
org.apache.iceberg.exceptions.ValidationException: Missing required files to delete: oss://masked-for-security-concern/data/_id_bucket_20=12/00000-0-5a087250-6137-4365-b5f9-9b04ceae2e47-305883.parquet,...dangling-delete-file-list-omitted 
	at org.apache.iceberg.exceptions.ValidationException.check(ValidationException.java:49) ~[iceberg-api-lilith-trino-1.6.1.1.jar:?]
	at org.apache.iceberg.ManifestFilterManager.validateRequiredDeletes(ManifestFilterManager.java:237) ~[iceberg-core-lilith-trino-1.6.1.1.jar:?]
	at org.apache.iceberg.ManifestFilterManager.filterManifests(ManifestFilterManager.java:199) ~[iceberg-core-lilith-trino-1.6.1.1.jar:?]
	at org.apache.iceberg.MergingSnapshotProducer.apply(MergingSnapshotProducer.java:837) ~[iceberg-core-lilith-trino-1.6.1.1.jar:?]
	at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:236) ~[iceberg-core-lilith-trino-1.6.1.1.jar:?]
	at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:386) ~[iceberg-core-lilith-trino-1.6.1.1.jar:?]
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413) ~[iceberg-core-lilith-trino-1.6.1.1.jar:?]
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219) ~[iceberg-core-lilith-trino-1.6.1.1.jar:?]
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203) ~[iceberg-core-lilith-trino-1.6.1.1.jar:?]
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196) ~[iceberg-core-lilith-trino-1.6.1.1.jar:?]
	at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:384) ~[iceberg-core-lilith-trino-1.6.1.1.jar:?]
	at org.apache.amoro.op.MixedUpdate.commit(MixedUpdate.java:143) ~[amoro-format-iceberg-0.8.0-incubating.jar:0.8.0-incubating]
	at org.apache.amoro.server.optimizing.maintainer.IcebergTableMaintainer.clearInternalTableDanglingDeleteFiles(IcebergTableMaintainer.java:477) ~[amoro-ams-0.8.0-incubating.jar:0.8.0-incubating]
	at org.apache.amoro.server.optimizing.maintainer.IcebergTableMaintainer.cleanDanglingDeleteFiles(IcebergTableMaintainer.java:336) ~[amoro-ams-0.8.0-incubating.jar:0.8.0-incubating]
	at org.apache.amoro.server.optimizing.maintainer.IcebergTableMaintainer.cleanDanglingDeleteFiles(IcebergTableMaintainer.java:162) ~[amoro-ams-0.8.0-incubating.jar:0.8.0-incubating]
	at org.apache.amoro.server.table.executor.DanglingDeleteFilesCleaningExecutor.execute(DanglingDeleteFilesCleaningExecutor.java:62) ~[amoro-ams-0.8.0-incubating.jar:0.8.0-incubating]
	at org.apache.amoro.server.table.executor.BaseTableExecutor.executeTask(BaseTableExecutor.java:82) ~[amoro-ams-0.8.0-incubating.jar:0.8.0-incubating]
	at org.apache.amoro.server.table.executor.BaseTableExecutor.lambda$null$0(BaseTableExecutor.java:72) ~[amoro-ams-0.8.0-incubating.jar:0.8.0-incubating]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_452]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_452]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_452]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_452]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_452]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_452]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_452]
```

### Affects Versions

0.8.1-incubating

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

Spark, Flink, AMS

### How to reproduce

1. Create an Iceberg table using Flink (mainly to enable upsert operations later by leveraging the primary key).
```sql
CREATE TABLE `iceberg`.`db`.`t` (
  `id` BIGINT COMMENT 'unique id',
  `data` STRING NOT NULL,
  PRIMARY KEY(`id`) NOT ENFORCED
) WITH (
  'format-version'='2',
  'write.upsert.enabled' = 'true',
  'identifier-fields' = '[id]'
);
```

2. Add a new partition column using Spark.
```
ALTER TABLE iceberg.db.t ADD PARTITION FIELD bucket(5, id);
```

3. Upsert a row in Flink. 
At this point, Flink will create an equality delete file and a data file containing the same id. Both files are written under the partition path id_bucket_5=<some_value>.
```sql
INSERT INTO iceberg.db.t /*+ OPTIONS('upsert-enabled'='true') */ values (5, '5');
```

4. Modify the partition column using Spark.
```sql
ALTER TABLE iceberg.db.t REPLACE PARTITION FIELD bucket(5, id) WITH bucket(10, id);
```

5. Upsert a row in Flink.
```sql
INSERT INTO iceberg.db.t /*+ OPTIONS('upsert-enabled'='true') */ values (5, '55');
```

6. Run clean-dangling-delete-files on this table in Amoro. 
Restarting Amoro can trigger the clean-dangling-delete-files operation, but once it starts, it immediately throws an error.
```
org.apache.iceberg.exceptions.ValidationException: Missing required files to delete: $warehouse_location/db.db/t/data/id_bucket_10=3/00000-0-2be57c08-cf6a-46c8-a93f-529f953138be-00002.parquet
        at org.apache.iceberg.exceptions.ValidationException.check(ValidationException.java:49)
        at org.apache.iceberg.ManifestFilterManager.validateRequiredDeletes(ManifestFilterManager.java:248)
        at org.apache.iceberg.ManifestFilterManager.filterManifests(ManifestFilterManager.java:200)
        at org.apache.iceberg.MergingSnapshotProducer.apply(MergingSnapshotProducer.java:838)
        at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:226)
        at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:376)
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
        at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
        at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:374)
        ...
```

### Relevant log output

```shell

```

### Anything else

The root cause is that in `org.apache.amoro.server.utils.IcebergTableUtil#getDanglingDeleteFiles`, the call to `org.apache.amoro.scan.TableEntriesScan#entries` returns an `IcebergFileEntry` whose `file()`'s `partition()` value is incorrect.

The underlying issue is in the implementation of `org.apache.amoro.scan.TableEntriesScan#buildDeleteFile`:
`fileRecord.get(dataFileFieldIndex(DataFile.PARTITION_NAME), StructLike.class)` returns values for all `PartitionSpec` columns, but the code assumes it only returns values for the columns in the current/latest `PartitionSpec`.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by j1wonpark**
## Why are the changes needed?

The entries metadata table returns a unified super-struct partition containing fields from all PartitionSpecs. In `TableEntriesScan`, both `buildDataFile()` and `buildDeleteFile()` passed this unified partition directly to `withPartition()`, which causes a partition struct mismatch for files written under a non-latest PartitionSpec. This is the root cause of #4044.

This PR fixes the issue at the `TableEntriesScan` level by projecting the unified partition to the spec-specific partition type using `StructProjection.createAllowMissing()`, so that all callers of `TableEntriesScan` get correct partition values regardless of spec evolution.

Close #4044.

## Brief change log

- Add `projectPartition()` method that uses `StructProjection.createAllowMissing()` to project the unified partition struct to the file's spec-specific partition type
- Apply the projection in both `buildDataFile()` and `buildDeleteFile()`
- Cache the unified partition type via `Partitioning.partitionType(table)` for reuse

## How was this patch tested?

- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible
- [ ] Add screenshots for manual tests if appropriate
- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
  no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  not applicable

### CODE REVIEW

**Comment by j1wonpark** [comment]
Hi @majin1102 @zhoujinsong, could you please review this PR? This fix addresses a partition mapping bug in `TableEntriesScan` for Iceberg tables with evolved PartitionSpec (AMORO-4044). Your expertise in this area would be greatly appreciated. Thanks!

**Comment by lintingbin** [comment]
We encountered the same issue internally and have tested this branch — all our internal tests passed. LGTM from the testing perspective.

One minor pre-existing issue I noticed (not introduced by this PR): the `LOG.info` calls in `buildDataFile()` and `buildDeleteFile()` use `%S` (printf-style) instead of `{}` (SLF4J-style) for the `filePath` parameter, so the file path is never actually substituted into the log message. I'll submit a separate PR to fix that.

**Comment by j1wonpark** [comment]
Hi @lintingbin, would you mind reviewing this PR?

It addresses the partition mismatch bug reported in #4044 — specifically fixing `TableEntriesScan` to correctly project the unified partition struct to each file's spec-specific partition type using `StructProjection.createAllowMissing()`.

Thanks!

**Comment by lintingbin** [comment]
https://github.com/apache/amoro/pull/4047 This PR is the fix proposed by our colleague, but I feel your solution is a better approach. We've already tested it internally on your branch, and everything looks good. I think it's ready to merge. @xxubai @zhoujinsong Please take a look at this.

File: amoro-format-iceberg/src/main/java/org/apache/amoro/scan/TableEntriesScan.java [hunk 1]
```diff
@@ -429,6 +432,20 @@ private int dataFileFieldIndex(String fieldName) {
     return lazyIndexOfDataFileType.get(fieldName);
   }
 
+  private StructLike projectPartition(PartitionSpec spec, StructLike partition) {
```
Comment (xxubai) [inline amoro-format-iceberg/src/main/java/org/apache/amoro/scan/TableEntriesScan.java:435]: It seems this function duplicates the logic in `PartitionUtil.coercePartition(...)`. Maybe we can reuse that method directly.

File: amoro-format-iceberg/src/main/java/org/apache/amoro/scan/TableEntriesScan.java [hunk 2]
```diff
@@ -372,7 +375,7 @@ private DeleteFile buildDeleteFile(StructLike fileRecord, FileContent fileConten
     if (spec.isPartitioned()) {
       StructLike partition =
           fileRecord.get(dataFileFieldIndex(DataFile.PARTITION_NAME), StructLike.class);
-      builder.withPartition(partition);
+      builder.withPartition(projectPartition(spec, partition));
```
Comment (xxubai) [inline amoro-format-iceberg/src/main/java/org/apache/amoro/scan/TableEntriesScan.java:378]:
```suggestion
      builder.withPartition(PartitionUtil.coercePartition(unifiedPartitionType(), spec, partition));
```

File: amoro-format-iceberg/src/main/java/org/apache/amoro/scan/TableEntriesScan.java [hunk 3]
```diff
@@ -340,7 +343,7 @@ private DataFile buildDataFile(StructLike fileRecord) {
...
```
Comment (xxubai) [inline amoro-format-iceberg/src/main/java/org/apache/amoro/scan/TableEntriesScan.java:346]:
```suggestion
      builder.withPartition(PartitionUtil.coercePartition(unifiedPartitionType(), spec, partition));
```

File: amoro-format-iceberg/src/main/java/org/apache/amoro/scan/TableEntriesScan.java (hunk 1 above)
Comment (j1wonpark) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/scan/TableEntriesScan.java:435]: Thanks for the suggestion! At first glance they do look similar, but the projection direction is actually reversed.

`coercePartition` projects **spec-specific → unified** (input: `spec.partitionType()`, output: `partitionType`):
```java
StructProjection.createAllowMissing(spec.partitionType(), partitionType);
```

`projectPartition` here projects **unified → spec-specific** (input: `unifiedPartitionType()`, output: `spec.partitionType()`):
```java
StructProjection.createAllowMissing(unifiedPartitionType(), spec.partitionType());
```

In `TableEntriesScan`, the `partition` data is read from the entries metadata table, which uses a unified partition schema (`Partitioning.partitionType(table)`). But `DataFiles.builder(spec).withPartition()` expects the spec-specific layout. So we need the unified → spec direction, which is the opposite of what `coercePartition` does.

Comment (xxubai) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/scan/TableEntriesScan.java:435]: make sense

**Review by xxubai — APPROVED** [review]
