### PR TITLE
[AMORO-3451] Fix kubernetes optimizer pod is frequently being killed

### LINKED ISSUE #3451: [Bug]: Kubernetes optimizer pod is frequently being killed
### What happened?

Kubernetes optimizer's JVM heap memory limit is the same as the pod memory limit, which is the cause of the issue.

### Affects Versions

master

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS, Optimizer

### How to reproduce

- Create a Kubernetes optimizer
- Schedule some task to it

### Relevant log output

```shell

```

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Marvel-Gu**
## Why are the changes needed?

Close #3451.

## Brief change log

In ams KubernetesOptimizerContainer, limit the size of the JVM heap memory to 80% of the pod's memory limit.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by Marvel-Gu** [comment]
I didn't format the code😂, I'll pay attention next time.

File: amoro-ams/src/main/java/org/apache/amoro/server/manager/KubernetesOptimizerContainer.java [hunk 1]
```diff
@@ -148,18 +148,23 @@ public Map<String, Object> generatePodStartArgs(
...
 
     if (resource.getMemoryMb() > 0) {
       memory = resource.getMemoryMb();
     } else {
       memoryPerThread = Long.parseLong(checkAndGetProperty(groupProperties, MEMORY_PROPERTY));
       memory = memoryPerThread * resource.getThreadCount();
     }
+
+    // reserving 20% of total pod memory for JVM non-heap memory
+    jvmHeapMemory = (long) (memory * 0.8);
```
Comment (czy006) [inline amoro-ams/src/main/java/org/apache/amoro/server/manager/KubernetesOptimizerContainer.java:161]: If we do not use off-heap memory in the code, I think it can be set to 0.9, which will not cause the container to be killed. If it is still frequently killed by OOM, we may need to check whether there is a memory leak in the code or the instantaneous Heap usage exceeds the container limit. We may be able to provide an external parameter for users to set, WDYT?

Comment (Marvel-Gu) [reply amoro-ams/src/main/java/org/apache/amoro/server/manager/KubernetesOptimizerContainer.java:161]: Sounds great, I'll work on it.

**Comment by zhoujinsong** [comment]
The default 80% configuration looks good to me. Maybe we can merge this PR now or do we have some other thing to validate before that? @Marvel-Gu @czy006

**Comment by czy006** [comment]
> The default 80% configuration looks good to me. Maybe we can merge this PR now or do we have some other thing to validate before that? @Marvel-Gu @czy006

This is indeed a black magic in the container. We can merge this PR now, and we may have a better way to solve it in the future.

> #3451

**Comment by Marvel-Gu** [comment]
> > The default 80% configuration looks good to me. Maybe we can merge this PR now or do we have some other thing to validate before that? @Marvel-Gu @czy006
> 
> This is indeed a black magic in the container. We can merge this PR now, and we may have a better way to solve it in the future.

This is the simplest and most effective solution I could think of for now. How do you think it could be improved?

File: charts/amoro/values.yaml [hunk 2]
```diff
@@ -278,6 +278,7 @@ optimizer:
       #kube-config-path: "~/.kube/config"
       image: "apache/amoro:latest"
       pullPolicy: "IfNotPresent"
+      jvm.heap.ratio: "0.8"
   extra: []
```
Comment (czy006) [inline charts/amoro/values.yaml:282]: I'm worried that our parameters will increase, can we put them into extra? Perhaps there is an additional map maintenance.

Comment (Marvel-Gu) [reply charts/amoro/values.yaml:282]: Yes, putting it in extra is a better approach, I will modify it

**Review by zhoujinsong — APPROVED** [review]
LGTM.
