### PR TITLE
[AMORO-3620][Improvement]: Fix the error in the calculation of the health score of table

### LINKED ISSUE #3620: [Improvement]: Fix the error in the calculation of the health score of table
### Search before asking

- [x] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Fix the issue where the health score calculation is incorrect when the table is empty.

### How should we improve?

Modify the calculation process of the health score.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cxxiii**
## Why are the changes needed?

Close #3620 .

## Brief change log

- Fix the issue where the health score calculation is incorrect when the table is empty.
    - when the table is empty, which means the number of table files equals to 0, the table is considered to be healthy and its health score should be 100. However, the actual displayed score is 0. This PR revised this problem.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/CommonPartitionEvaluator.java [hunk 1]
```diff
@@ -434,7 +434,7 @@ private double getTablePenaltyFactor(long dataFiles, long dataFilesSize) {
     // The small table has very little impact on performance,
     // so there is only a small penalty
     return getNormalizedRatio(dataFiles, config.getMinorLeastFileCount())
-        * getNormalizedRatio(dataFilesSize, config.getTargetSize());
+        * getNormalizedRatio(dataFilesSize, minTargetSize);
```
Comment (zhoujinsong) [inline amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/CommonPartitionEvaluator.java:437]: Hi, can you give some reason why we should change here?

**Comment by zhoujinsong** [comment]
@MarigWeizhi Can you help to review this PR?

**Comment by MarigWeizhi** [comment]
1. I've tested locally and just need to modify one place: `avgHealthScore`, which should return 100 when partitionCount is 0. 
2. I'm not sure if it's necessary to change `targetSize` to `minTargetSize`

File: amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/CommonPartitionEvaluator.java (hunk 1 above)
Comment (cxxiii) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/CommonPartitionEvaluator.java:437]: I change here according to the computational formula of TablePenaltyFactor in https://github.com/apache/amoro/issues/3180 . I think there must have been a typing error before.

**Comment by cxxiii** [comment]
> 1. I've tested locally and just need to modify one place: `avgHealthScore`, which should return 100 when partitionCount is 0.
> 2. I'm not sure if it's necessary to change `targetSize` to `minTargetSize`

1、I changed `targetSize` to `minTargetSize` according to the computational formula of TablePenaltyFactor in https://github.com/apache/amoro/issues/3180 . I think there must have been a typing error before.
2、I also changed the computational formula of averageDataFileSize according to the description provided in https://github.com/apache/amoro/issues/3180 . In the original code's calculation formula, the value of averageDataFileSize was incorrectly set to be less than or equal to 1. I made the necessary adjustments.

File: amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/CommonPartitionEvaluator.java [hunk 2]
```diff
@@ -397,7 +397,7 @@ public int getHealthScore() {
     long dataFiles = getFragmentFileCount() + getSegmentFileCount();
     long dataRecords = getFragmentFileRecords() + getSegmentFileRecords();
 
-    double averageDataFileSize = getNormalizedRatio(dataFilesSize, dataFiles);
+    double averageDataFileSize = dataFilesSize / dataFiles;
```
Comment (MarigWeizhi) [inline amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/CommonPartitionEvaluator.java:400]: Is it possible for dataFiles to be 0 ？

Comment (MarigWeizhi) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/CommonPartitionEvaluator.java:400]: > Is it possible for dataFiles to be 0 ？

I tested it locally, and when there is no data in the partition, this line of code is unreachable, so dataFiles will not be 0.

**Comment by MarigWeizhi** [comment]
> > 1. I've tested locally and just need to modify one place: `avgHealthScore`, which should return 100 when partitionCount is 0.
> > 2. I'm not sure if it's necessary to change `targetSize` to `minTargetSize`
> 
> 1、I changed `targetSize` to `minTargetSize` according to the computational formula of TablePenaltyFactor in #3180 . I think there must have been a typing error before. 2、I also changed the computational formula of averageDataFileSize according to the description provided in #3180 . In the original code's calculation formula, the value of averageDataFileSize was incorrectly set to be less than or equal to 1. I made the necessary adjustments.

LGTM

File: amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/CommonPartitionEvaluator.java (hunk 2 above)
Comment (cxxiii) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/CommonPartitionEvaluator.java:400]: I think it's impossible. The partition without dataFiles will not appear in the scan results, nor will the PartitionEvaluator for that partition be created.

File: amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/CommonPartitionEvaluator.java (hunk 1 above)
Comment (zhoujinsong) [reply amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/CommonPartitionEvaluator.java:437]: Makes sense to me.
